spring:
  datasource:
    url: jdbc:sqlserver://hakatonserver.database.windows.net:1433;database=hakatonbaza;
    username: hakaton
    password: Baza123$
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false